name: mkidcal
channels:
  - defaults
  - conda-forge
dependencies:
    - ipython
    - numpy
    - scipy
    - tensorflow
    - keras
    - matplotlib
    - ruamel.yaml
    - multiprocessing-logging
    - parse

